# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: '1234'
  DATABASE_HOST: 'localhost'

  SECRET_KEY_BASE: '6542420d5caf68fafba1251f3391c881471c7166599addcb5541fc86470cbb31a619c164237fbb7a192fa6f7299766020cc2aebf31b269969e98602c9b740492'

  REDIS_NAMESPACE: 'user_tracking_dev_cache'
  REDIS_URL: 'redis://localhost:6379'
  REDIS_DB: '2'

test:
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: '1234'
  DATABASE_HOST: 'localhost'

  SECRET_KEY_BASE: '3fa0a8ad38037a294dbf2abf124a654283af2afd28c074148488b21808cfb54c9441c6aedd8dbcafb5a2fe62ff6313e6c6d53c425aa2572352d16aff1ea372f7'

  REDIS_NAMESPACE: 'user_tracking_test_cache'
  REDIS_URL: 'redis://localhost:6379'
  REDIS_DB: '3'

production:
  DATABASE_USER:
  DATABASE_PASSWORD:

  SECRET_KEY_BASE:

  REDIS_NAMESPACE:
  REDIS_URL:
  REDIS_DB:
